### ISSUE TITLE
tests/main.c freezes inside scale_zero

### ISSUE THREAD

**Issue by ali1234** [endail/pico-scale#7]
Checking the source, the reason is here:

https://github.com/endail/pico-scale/blob/898dc156873d6bf1b8cda9c1cd299bb89c362a1b/src/scale.c#L131

This while loop can never be exited because timeout is always 10 seconds on each loop. The absolute time at which the timeout ends is always 10 seconds from the point of calling the function: https://github.com/endail/hx711-pico-c/blob/main/src/hx711.c#L301 - ie inside the call.

So this while loop will keep reading until the realloc fails, at which point the pico seems to crash.

**Comment by ali1234** [comment]
In fact if you watch the serial long enough it eventually does this, which confirms it:

```

*** PANIC ***

Out of memory
```

Note that calibration.c works okay, because it uses a sample count rather than a timeout.

**Comment by endail** [comment]
Thanks! Will definitely fix this.

**Comment by endail** [comment]
Fixed in https://github.com/endail/pico-scale/commit/b979211f534ee6556b3992e406da4e13fda70f62
